#+TITLE:Alex Harter Resume
#+PROPERTY: header-args :tangle ~/Projects/Resume/resume.typ
- This file should be treated as the source of truth for my resume content
- For now, the primary target is the pdf generated by tangling typst source blocks
  - I choose this approach because
    - I'm still learning latex and org-export
    - It's still relatively direct, while taking advantage of org's notetaking, task, export control, and links
    - I can export this file, annontations and all, for interview prep
  - In the future, I may experiment with ox-latex or ox-html
- For some systems, I may need to export a docx file, in which case I can use pandoc or manually make the google doc match

- Helpful links:
  - [[https://typst.app/docs/reference/][Typst Docs]]
  - [[https://github.com/GeorgeHoneywood/alta-typst][alta-typst template]]
  - [[https://www.nerdfonts.com/cheat-sheet][nerd font icons]]
* Compile
#+BEGIN_SRC elisp :tangle no :results no
  (shell-command "typst compile resume.typ")
  (shell-command "brave resume.pdf")
#+END_SRC

#+RESULTS:
: 0

* Typst Setup
#+BEGIN_SRC typst-ts
  #set page("us-letter")
  #set page(columns: 2)
  #set list(marker: ([󱞩]))
#+END_SRC
* Title
- can I export this to both the resume and cover letter?
  - not directly, so I'll simply have to deal with that separately
IT Specialist

#+BEGIN_SRC typst-ts
  #place(
    top + center,
    scope: "parent",
    float: true,
    text(1.4em, weight: "bold")[
      ALEX HARTER \
      IT Specialist
    ],
  )

  //#align(center)[= ALEX HARTER]
  //#align(center)[== IT Specialist]

#+END_SRC

* Header Info
#+BEGIN_SRC typst-ts
  #place(
    top + left,
    scope: "parent",
    float: true,
    text()[
      #columns(2)[
	 #h(5%) Houston, TX _(Wanting to Relocate to DFW)_ \
	// Houston, TX
	 #h(5%) #link("https://alex.harter.tech")[alex.harter.tech] \
	 #h(5%) #link("https://github.com/AlexHarter")[AlexHarter] \
	#colbreak()
	󰇮 #h(5%) #link("mailto:alex@harter.tech")[alex\@harter.tech] \
	 #h(5%) #link("https://linkedin.com/in/alexhartertech")[alexhartertech] \
	 #h(5%) (940) 597-4771
      ]
    ],
  )
#+END_SRC
- my website definitely needs to be updated
  - well, I can export this file to HTML to make it easy
- Switch Commerce had issues sending me emails, and I never figured out why...
  - [ ] ask Dad about it
- my LinkedIn needs to be updated
* Summary
#+BEGIN_SRC typst-ts
  = SUMMARY
  Dedicated and versatile technology professional with experience in fintech, music, and education.
  Proven ability to quickly learn and apply a variety of technical skills combined with competent oral and written communication both as a leader and as part of a team.
  Passion for serving clients to solve technical problems effectively.
  
#+END_SRC
- add data somewhere here?
* Experience
#+BEGIN_SRC typst-ts 
  = EXPERIENCE
  == Choral Music Specialist | November 2021 - Present
  // Change start date? The current one is when I started leading the St Sophia Choir, but I've been doing these things for a lot longer
  // I think I like "Choral Music Specialist" the best, but I still don't love it...
  // - I mean, employers might just think, why would we hire a musician?
  _Self-Employed_
  - _Software_ - Utilize publishing and audio software to create and transmit sheet music, service booklets, and recordings.  Implemented morning service booklet which is now used every week.
  - _Performance & Leadership_ - Lead choirs in various services by singing, conducting, and giving directions in order to make services more orderly and encourage participation.  Plan and lead rehearsals.
  // - _Mentoring & Collaboration_ - Suggest operational improvements and share resources with other choir directors.  Collaborate with experts in the field.  Working on adapting Latin and Slavonic chants into Spanish and English; producing a critical edition of Gregorian chant according to 1st millennium manuscripts.
  - _Education & Teaching_ - Educate myself and others about musical, linguistic, and historical aspects of Ukrainian and Latin church singing through primary source documents, academic papers, lectures, and communicating with experts.  Learned Cyrillic alphabet as well as old and new Gregorian and Kyivan notations.

  == Data Automation Consultant | July 2022 - February 2023
  _Encapture | Dallas, TX_
  - _Data Extraction_ - Extracted client-requested information from received documents sorted by classification algorithms then validated and translated that data according to customer specifications.
  - _Configuration of Pipeline_ - Configured internal software within Amazon Web Services to receive and sort customer documents and apply appropriate automation templates at multiple stages.
  - _Presentation_ - Demoed in-progress pipelines to clients to present progress, ask questions, and teach how to interface with the products.  Communicated internal software issues to the Product team with ideas for improvement for various clients.
  - _Documentation_ - Edited and contributed to documentation on Classification software for internal/client use.
  - _Team-Building_ - Started a book club with co-workers to improve professional and personal skills.

  == Choir Teacher / Special Education Paraprofessional | September 2019 - November 2021
  _Responsive Education Solutions | Founders Classical Academy of Corinth_
  
#+END_SRC
* Education
#+BEGIN_SRC typst-ts
  = EDUCATION
  == CompTIA A+ - Core 1 Passed; Core 2 In Progress
  == Post-Graduate Certificate in Data Science & Business Analytics | August 2023 - April 2024
  _University of Texas at Austin_
  - Curriculum included Python; Data Analysis with Pandas; Data Visualization with Seaborn; Statistics with NumPy; and Machine Learning with SciKit Learn
  == Texas Educator Content Certified in Music EC-12 & Special Education EC-12
  == Bachelor of Science in Rehabilitation Studies | Minor in Music | Cumulative GPA: 3.74
  _University of North Texas | Denton, TX | Graduated Magna Cum Laude December 2019_
  - Coursework included Statistics, Case Management, Special Education, and Music Theory & Composition
  #colbreak()
#+END_SRC
* Projects
- Python/Programming - GregoLy
- Data Science - Easy Visa
  - I chose EasyVisa because the unstructured data projects don't show off bivariate analysis as much
- Publishing - Abridged Sunday Matins
#+BEGIN_SRC typst-ts
  = PROJECTS
  == #link("https://github.com/AlexHarter/gabc-to-ly")[GregoLy] - _for #link("https://cantatorium.com/proper")[Cantatorium]_ _(in progress)_
  - Python script to convert gabc files in Gregorian notation to LilyPond in modern notation
  == #link("https://drive.google.com/file/d/1Za7x0-2vl2OxEasvwTA5qceroc40SfqY/view?usp=sharing")[EasyVisa] - _for Data Science & Business Analytics Certificate_
  - Jupyter notebook demonstrating bivariate data analysis and training machine learning models on structured data
  == #link("https://docs.google.com/document/d/1l8XWQ-jQBbqBsF7uaxrgpa1TADOuKCNeTwAStFmAcoo/edit?usp=sharing")[Abridged Sunday Matins Booklet] - _for St. Sophia Ukrainian Catholic Church_
  // I'd love it if this could be done in LaTeX
  - Morning service booklet including music adapted from Slavonic to English, currently used every week
  
#+END_SRC
* Skills & Interests
- I've heard this section is a good chance to nerd out about things during the interview that wouldn't otherwise come up
#+BEGIN_SRC typst-ts
  = SKILLS & INTERESTS
  - *Technical Skills:*  #h(5%) Python,  #h(5%) Linux,  #h(5%) Git, Regular Expressions, Data Analysis, Machine Learning, Office Software, Publishing Software, Audio Software
  - *Soft Skills:* Agile, Getting Things Done, Personal Information Management, Project Management, Teamwork, Communication, Attention to Detail, Problem Solving, Customer Service
  - *Interests:*  #h(5%) Emacs,   #h(5%) Music Theory, 󰠬 #h(5%) Karate
  // birding?

#+END_SRC

-----

#+BEGIN_COMMENT
I feel embarrased I don't have more projects to show.  Alma suggested to look up positives to having ADHD and work that into my resume.  I could focus on getting my half-finished projects to minimum viable product level as quickly as I can.

I also feel a bit lost and my job title and really how to market myself.  I did this Data Science certificate, but now I'm working on my A+, which is kind of a different thing.  Add music to that, and I look like a mess.
- Potential titles:
  - IT Specialist
    - For this play up my customer service, and personal passion, e.g. homelab, Linux, music stuff
    - Maybe add something like "IT/Data"?
      - But again, an employer is going expect Excel and SQL, and probably Cloud too
  - Data Analyst
    - I feel like I can't use this until I have an Excel project
  - Data Scientist
  - Python Developer
    - Really emphasize my certificate with the DS libraries
    - I feel like I need a more significant project though
- Final Decision: IT Specialist
  - it's the one I'm most qualified for, because I am a jack of all trades right now, and the Python/Data stuff defnitely still looks good
- for each of the "claims" on my resume, make comment about which story illustrates it, just like a persuasive essay
#+END_COMMENT
